### ISSUE TITLE
Deal with `.gitattributes` changing `batect.cmd`'s line endings

### ISSUE THREAD

**Issue by sschuberth** [batect/batect-wrapper-validation-action#10]
The check seems to expect `batect.cmd` to have Unix (LF) line endings. However, with `batect.cmd` being a Windows-only file, it's usually committed with LF endings, but a `.gitattributes` configures the checkout in the working tree to happen with Windows (CR/LF) line endings.

I'm not sure yet what the best solution is. Maybe it makes sense to check how https://github.com/gradle/wrapper-validation-action does it for `gradlew.bat`. But my hunch is that this action should simply expected CR/LF endings for `batect.cmd`.

**Comment by charleskorn** [comment]
Do you have a sample repo that shows the issue you're running into @sschuberth?

This action doesn't do anything with line endings - it reads the files from disk and computes checksums for them without applying any transformation or interpretation. 

I've also just double-checked that the checksum published with each release is based on a `.cmd` file with Windows line endings (CR/LF), and changing `batect.cmd` to have Unix line endings (LF) changes the checksum and fails validation, as expected.

**Comment by charleskorn** [comment]
I've added an extra warning that will alert you if the line endings the action is seeing is not what it expects - please try [v0.4.0](https://github.com/batect/batect-wrapper-validation-action/releases/tag/v0.4.0) and see if that helps track down the issue.

**Comment by sschuberth** [comment]
> Do you have a sample repo that shows the issue you're running into @sschuberth?

Yes, you can see the failed check in this repo / check:

https://github.com/oss-review-toolkit/ort/runs/6147616777?check_suite_focus=true#step:4:6

> I've also just double-checked that the checksum published with each release is based on a `.cmd` file with Windows line endings (CR/LF), and changing `batect.cmd` to have Unix line endings (LF) changes the checksum and fails validation, as expected.

Interesting. After a checkout of ... I get

```
$ sha256sum batect.cmd
bc2db2ca004b71059241ac2e40bfadb542e5c8ba5abd2af1ee69ae3d3b3385a5 *batect.cmd
```

which operates on the file with CR/LF endings, but

```
$ git show HEAD:batect.cmd | sha256sum
8d98983c9d36a554893d5834ffd67499cc0ef813a7642248a204a03d2de3101f *-
```

which operates on the file contens as committed to Git (i.e. with LF endings only).

The message says the former would be the expected checksum (which is correct), but calculated was the latter.

**Comment by sschuberth** [comment]
> I've added an extra warning that will alert you if the line endings the action is seeing is not what it expects - please try [v0.4.0](https://github.com/batect/batect-wrapper-validation-action/releases/tag/v0.4.0) and see if that helps track down the issue.

I'm now [seeing that extra warning](https://github.com/oss-review-toolkit/ort/runs/6152710953?check_suite_focus=true#step:4:6):

> Error: Windows wrapper script 'batect.cmd' has SHA256 checksum 8d98983c9d36a554893d5834ffd67499cc0ef813a7642248a204a03d2de3101f, but it should have SHA256 checksum bc2db2ca004b71059241ac2e40bfadb542e5c8ba5abd2af1ee69ae3d3b3385a5. 'batect.cmd' appears to have Unix-style line endings (LF) instead of Windows-style line endings (CR/LF), which may be causing this mismatch.

Could it be the checkout action itself that messes this up? I'll try to investigate.

**Comment by sschuberth** [comment]
> Could it be the checkout action itself that messes this up? I'll try to investigate.

According to [this comment](https://github.com/actions/checkout/issues/135#issuecomment-889903667) the checkout action respects `.gitattributes`. I double-checked things on my side, and we indeed seem to be missing according entries in `.gitattributes` for `*.cmd` (and `*.bat`) although I was 100% sure we had them. I'll make that change and report back.

**Comment by sschuberth** [comment]
Yes, adding those `.gitattribute` entries [fixed the wrapper validation](https://github.com/oss-review-toolkit/ort/runs/6152940716?check_suite_focus=true#step:4:6). Sorry for the noise... but thanks for adding that valuable warning about line endings anyway!

**Comment by charleskorn** [comment]
Glad to hear it, happy to help!
