### ISSUE TITLE
Please say why type of checksum fails

### ISSUE THREAD

**Issue by sschuberth** [batect/batect-wrapper-validation-action#9]
When the check fails the message is like

> Windows wrapper script 'batect.cmd' has checksum 8d98983c9d36a554893d5834ffd67499cc0ef813a7642248a204a03d2de3101f, but it should have checksum bc2db2ca004b71059241ac2e40bfadb542e5c8ba5abd2af1ee69ae3d3b3385a5.

For manual verification / debugging it would be nice to know of which type the checksum is. Could you extend the message to say it's a SHA256?

**Comment by charleskorn** [comment]
Great idea, I've just added this. Thanks @sschuberth!
